version: '3'
services:
  dnsmasq:
    image: angelx/dnsmasq:0.0.1
    cap_add:
    - NET_ADMIN
    network_mode: "host"
#  vault:
#    image: vault:0.7.3
#    cap_add:
#    - IPC_LOCK
#    environment:
#      VAULT_DEV_ROOT_TOKEN_ID: myroot
#      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:1234
#      VAULT_LOCAL_CONFIG: '{"backend": {"file": {"path": "/vault/config"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}'
#    ports:
#    - "1234:1234"
#    command: vault server
