cert-gen:
	./bin/cert-gen
install-certs:
	./bin/install-certs
parse-clc:
	./bin/parse-clc-files
http-cert-server:
	python2 -m SimpleHTTPServer 8000
ssh-master0:
	ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -lcore 192.168.1.100
