kind: Config
clusters:
- name: local
  cluster:
    certificate-authority: /etc/kubernetes/ssl/ca.pem
    server: ${server}
users:
- name: kubelet
  user:
    client-certificate: /etc/kubernetes/ssl/${client_cert}
    client-key: /etc/kubernetes/ssl/${client_key}
contexts:
- context:
    cluster: local
    user: kubelet
  name: kubelet-cluster.local
current-context: kubelet-cluster.local
